### ISSUE TITLE
Who is the primary maintainer for this project?

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/jenkins-scripts#96]
I'm curious who the primary maintainer is of this project.  If there's not currently a primary maintainer then I would like to volunteer to be the primary maintainer.

If there is already a primary maintainer I would like to be a sub-maintainer and collaborate.

Please let me know.

**Comment by samrocketman** [comment]
cc @imod I notice you have recently merged PRs on this project.  Are you the maintainer?

**Comment by imod** [comment]
As I'm the maintainer of the scriptler plugin and this repo (until now) mostly contains scripts which can be imported by scriptler - I usually check this repo every couple of weeks. But since scriptler currently is not in the update center anymore (bc. security issues) I did not check this repo either. 
I'm not sure when scriptler will be back in the UC again. But if you would like to maintain this repo, please feel free to do so - I think you need to send a PR to https://github.com/jenkins-infra/repository-permissions-updater to get the permissons granted.

**Comment by samrocketman** [comment]
Okay, great.  In general, I personally use this as a reference for building out script console scripts and not just for use in scriptler.

**Comment by Dmitry1987** [comment]
Does this mean Scriptler is dead?  it was such a nice plugin, I was surprised to see it's not available anymore... for some internal safe use, I don't even care about these vulnerabilities listed :) in a team of 3 (where I work now) we don't even care :))))

**Comment by imod** [comment]
@Dmitry1987 no scriptler is not dead - in fact all issues are fixed now and I will soon do a release with all the issues addressed

**Comment by Dmitry1987** [comment]
🥇

**Comment by samrocketman** [comment]
Closing since @imod still expresses interest in maintaining it.  I have no need to maintain the plugin if someone else is going to.
